import { useEffect } from 'react'
import Head from 'next/head'

export default function Home() {
  useEffect( () => { 
    document.querySelector("body").classList.add(
        "bg-gradient-to-r",
        "from-pink-500",
        "to-orange-500"
      )} 
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="columns-3 px-15">
        <img className="w-full" src="https://s3.ap-northeast-1.amazonaws.com/assets.zhangt.ai/images/cherry.webp" alt="" />
        <div className='flex items-center'>
          TYING.US
        </div>
        <img className="w-full scale-x-[-1]" src="https://s3.ap-northeast-1.amazonaws.com/assets.zhangt.ai/images/cherry.webp" alt="" />
        {/* <Image className="w-full aspect-square" src="..." alt="" /> */}
      </div>
    </div>
  )
}
